server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: pedidos-route
              uri: lb://MICROSERVICE-PEDIDOS
              predicates:
                - Path=/pedidos/**

            - id: produtos-route
              uri: lb://MICROSERVICE-PRODUTOS
              predicates:
                - Path=/produtos/**

eureka:
  instance:
    appname: api-gateway
  client:
    service-url:
      defaultZone: https://discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true